// coin data
export const GET_COIN_DATA = "GET_COIN_DATA";
export const GET_COIN_DATA_SUCCESS = "GET_COIN_DATA_SUCCESS";
export const GET_COIN_DATA_FAIL = "GET_COIN_DATA_FAIL";
export const GET_COIN_AND_USER_FROM_STORAGE = 'GET_COIN_AND_USER_FROM_STORAGE';
export const GET_COIN_AND_USER_FROM_STORAGE_SUCCESS = 'GET_COIN_AND_USER_FROM_STORAGE_SUCCESS';
export const GET_COIN_AND_USER_FROM_STORAGE_FAIL = 'GET_COIN_AND_USER_FROM_STORAGE_FAIL';
// news data
export const GET_NEWS_DATA = "GET_NEWS_DATA";
export const GET_NEWS_DATA_SUCCESS = "GET_NEWS_DATA_SUCCESS";
export const GET_NEWS_DATA_FAIL = "GET_NEWS_DATA_FAIL";

// portfolio
export const SET_COIN_FROM_STORAGE = 'SET_COIN_FROM_STORAGE';

export const ADD_COIN_DONE = 'ADD_COIN_DONE';
export const ADD_COIN_FAIL = 'ADD_COIN_FAIL';
export const ADD_COIN_FIELD_UPDATE = 'ADD_COIN_UPDATE'; // called when a field is typed into


export const DELETE_COIN = 'DEL_COIN';
export const GET_COIN = 'GET_COIN';